学習管理アプリ課題
miu-ikeuchi/learning_plan pull request #1
Opened 2021-05-03 10:08 UTC by miu-ikeuchi

SQLSTATE[HY000]: General error: 1364 Field 'due_date' doesn't have a default valueSQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '' for column 'due_date' at row 1
上記のエラーが出てしまって、どの部分を変更すればエラーが解消できるのか調べても理解出来ませんでした。
ご教示ください。

2021-05-03 11:15 UTC, yukishimizumg commented
@miu-ikeuchi 
データを登録する際に、`title`と`due_date`をバラバラで追加しようとしているためです。
1レコードを追加するときに、必要なフィールドを1回で挿入できるように修正してください✨
(insertPlan関数とinsertDue関数を1つにまとめてください)

```php
insertPlan($title);
insertDue($due_date);
↓
insetLeaningPlan($title, $due_date);
```

2021-05-03 11:16 UTC, yukishimizumg commented on functions.php
> +            (title);
パラメータをバインドしてください✨

2021-05-05 13:35 UTC, kazu-taka requested changes
@miu-ikeuchi 
コード凄い綺麗で見やすいです✨
一部コメントしたので確認お願いします:bow:

2021-05-05 13:35 UTC, kazu-taka commented on functions.php
> +        due_date ASC;
@miu-ikeuchi 
完了データの表示順は「完了日の降順でデータを表示」という仕様ですので、修正お願いします:bow:

2021-05-05 13:35 UTC, kazu-taka commented on index.php
> +$completed_plans = findPlanByCompDate(PLAN_DATE_COMP);
@miu-ikeuchi 
どちらの関数も引数を用意していないので、こちらで渡している値は削除してOKです！
また、削除したことにより、定数を使用しない場合は、定数の削除もお願いします:bow:

2021-05-05 13:35 UTC, kazu-taka commented on style.css
> +}
@miu-ikeuchi 
レスポンシブ対応いずれやらないといけないので、対応お願いします:bow:

2021-05-16 03:57 UTC, merged