学習管理アプリ
miu-ikeuchi/learning_plan pull request #2
Opened 2021-05-11 13:49 UTC by miu-ikeuchi

レスポンシブデザインに関して
ボタンのサイズ指定が上手くいかず完成していません
機能部分は完了したので確認よろしくおねがいします

2021-05-11 13:51 UTC, kazu-taka commented
@miu-ikeuchi 
>レスポンシブデザインに関して
ボタンのサイズ指定が上手くいかず完成していません

うまくいっていない現状のスクショを貼ってもらってもいいですか？:bow:

2021-05-12 11:00 UTC, miu-ikeuchi commented
![image](https://user-images.githubusercontent.com/71203566/117964509-a914ae00-b35c-11eb-9af9-58b1af25f92c.png)

2021-05-12 11:01 UTC, miu-ikeuchi commented
レスポンシブの方は現状こんな漢字です

2021-05-12 23:51 UTC, kazu-taka requested changes
@miu-ikeuchi 
非常にコード見やすかったです！！
レスポンシブデザインのところは、引き続きお願いします✨

2021-05-12 23:51 UTC, kazu-taka commented on style.css
> +}
@miu-ikeuchi 
レスポンシブデザインはまだ調整中ということでしたが、以下のように、メディアクエリの中はインデントするようにお願いします:bow:
```css
@media (max-width: 800px) {
     /* 外枠 */
    .form-area,
    .incomplete-area,
```

2021-05-14 12:44 UTC, kazu-taka commented on index.php
> +                            <td><a href="delete.php?id=<?= h($plan['id']) ?>" class="btn delete-btn">削除</a></td>
@miu-ikeuchi 
ボタンのデザインが崩れている件ですが、aタグはインライン要素にあたるため、幅や高さを指定する場合は、`display: block;`でブロック要素に変更する必要があります！
ブロック要素に変更したうえで、幅や高さを指定してみて下さい✨
https://www.itra.co.jp/webmedia/block-inline-difference.html#id2

2021-05-15 00:23 UTC, kazu-taka commented
@miu-ikeuchi 
レスポンシブも問題ありませんでした✨
今回は修正しなくても良いですが、インプットフィールドは、paddingを指定した方がデザインが良くなるので、次回は試してみて下さい👍

### 修正前

<img width="783" alt="スクリーンショット 2021-05-15 9 20 09" src="https://user-images.githubusercontent.com/5278718/118342626-0b3d0100-b55f-11eb-8d70-d0d3d3a72936.png">


### 修正後

<img width="799" alt="スクリーンショット 2021-05-15 9 20 02" src="https://user-images.githubusercontent.com/5278718/118342614-011b0280-b55f-11eb-935b-10552b05989c.png">

2021-05-15 02:37 UTC, merged